# Per-column DQ rule definitions for source1, in the shape:
# Column_name: { DimensionClassName: { rule: ..., params: {...} } }


order_id:
  Completeness:
    rule: is_not_null


placed_time:
  Completeness:
    rule: is_not_null